run:
  tests: true

linters:
  enable-all: true
  disable:
    - depguard # : Go linter that checks if package imports are in a list of acceptable packages [fast: false, auto-fix: false]
    - forbidigo # : Forbids identifiers [fast: true, auto-fix: false]
    - funlen # : Tool for detection of long functions [fast: true, auto-fix: false]
    - gochecknoglobals # : check that no global variables exist [fast: true, auto-fix: false]
    - gochecknoinits # : Checks that no init functions are present in Go code [fast: true, auto-fix: false]
    - godox # : Tool for detection of FIXME, TODO and other comment keywords [fast: true, auto-fix: false]
    - goerr113 # : Golang linter to check the errors handling expressions [fast: false, auto-fix: false]
    - goprintffuncname # : Checks that printf-like functions are named with `f` at the end [fast: true, auto-fix: false]
    - lll # : Reports long lines [fast: true, auto-fix: false]
    - nlreturn # : nlreturn checks for a new line before return and branch statements to increase code clarity [fast: true, auto-fix: false]
    - tagliatelle # : Checks the struct tags. [fast: true, auto-fix: false]
    - testpackage # : linter that makes you use a separate _test package [fast: true, auto-fix: false]
    - varnamelen #: checks that the length of a variable's name matches its scope [fast: false, auto-fix: false]
    - wsl # : Whitespace Linter - Forces you to use empty lines! [fast: true, auto-fix: false]

linters-settings:
  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
